
const MAX_VERSION_SEMANTIC = 3
const MAX_VERSION_SEMANTIC_VALUE = 99;
const MAX_TAG_STRING_LENGTH = MAX_VERSION_SEMANTIC * MAX_VERSION_SEMANTIC_VALUE.toString().length + (MAX_VERSION_SEMANTIC - 1);

export {
    MAX_VERSION_SEMANTIC,
    MAX_VERSION_SEMANTIC_VALUE,
    MAX_TAG_STRING_LENGTH
}